CREATE DATABASE TaskHive;

USE TaskHive;

CREATE TABLE Users (
userID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
userName VARCHAR(100) NOT NULL UNIQUE,
email VARCHAR(150) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Tasks (
taskID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
userID INT NOT NULL,
title VARCHAR(255) NOT NULL,
description TEXT,
priority ENUM('None', 'Low', 'Medium', 'High') DEFAULT 'None',
category VARCHAR(100) DEFAULT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
dueDate DATE DEFAULT NULL,
completed ENUM('Pending start', 'Current', 'Completed') DEFAULT 'Pending start',
is_recurring BOOLEAN DEFAULT FALSE,       
repeat_interval INT DEFAULT NULL,         
recur_rule VARCHAR(100) DEFAULT NULL,     
FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE
);

CREATE TABLE Task_Completions (
  completionID INT AUTO_INCREMENT PRIMARY KEY,
  taskID INT NOT NULL,
  completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (taskID) REFERENCES Tasks(taskID) ON DELETE CASCADE
);
